# config.yaml
dataset_dir: "C:/Users/rmanr/Documents/GitHub/pomelo-disease-classification/Dataset/"        # path to the folder with subfolders Anthracnose, Borer, Canker, Mite, Healthy
output_dir: "C:/Users/rmanr/Documents/GitHub/pomelo-disease-classification/Models/ChatGPT/outputs"
image_size: 224
batch_size: 32
epochs: 5
fine_tune_epochs: 8
learning_rate: 0.0001
fine_tune_learning_rate: 0.00001
validation_split: 0.1   # fraction for val and test each after initial split (we will do 80/10/10)
random_state: 42
svm_kernel: "rbf"
svm_C: 1.0
svm_gamma: "scale"
checkpoint_name: "efficientnetb0_finetuned.keras"
save_plots: true
use_gpu: true
seed: 42